// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqnvqmdaqiwogjaawuwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxbnZxbWRhcWl3b2dqYWF3dXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0OTExODgsImV4cCI6MjA4ODA2NzE4OH0.a7oJPJxhniPYthV-UW6N9Ml6pU3FxgHNNmLq0sa3I0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});